server:
  port: 12004

spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 192.168.12.59:8848
      discovery:
        username: nacos
        password: nacos
        namespace: dev